; This file was auto-generated by drush_make
api = 2
core = 7.x

includes[] = project-core.make

; Modules
projects[views_bulk_operations][version] = "3.4"

projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][version] = "1.7"

projects[adminimal_admin_menu][version] = "1.7"

projects[breakpoints][version] = "1.4"

projects[ctools][version] = "1.12"

projects[ckeditor][version] = "1.17"

projects[ckeditor_link][version] = "2.4"

projects[date][version] = "2.10"

projects[ds][version] = "2.14"

projects[email][version] = "1.3"

projects[entity][version] = "1.8"

projects[entityreference][version] = "1.1"

projects[fences][version] = "1.2"

projects[field_group][version] = "1.5"

projects[picture][version] = "2.13"

projects[google_analytics][version] = "2.3"

projects[imagestyleflush][version] = "1.2"

projects[imce][version] = "1.11"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.7"

projects[libraries][version] = "2.3"

projects[link][version] = "1.4"

projects[manualcrop][version] = "1.6"

projects[menu_block][version] = "2.7"

projects[module_filter][version] = "2.1"

projects[pathauto][version] = "1.3"

projects[phone][version] = "1.x-dev"

projects[redirect][version] = "1.0-rc3"

projects[token][version] = "1.7"

projects[views][version] = "3.16"

projects[views_load_more][version] = "1.5"

projects[webform][version] = "4.15"

projects[xmlsitemap][version] = "2.3"


projects[civicrm][download][type] = "git"
projects[civicrm][download][url] = "https://github.com/civicrm/civicrm-core.git"
projects[civicrm][download][tag] = "4.6.19"
projects[civicrm][type] = "module"
projects[civicrm][subdir] = "custom"
projects[civicrm][patch][] = "https://raw.githubusercontent.com/ubc-web-services/CBM_Plugin_for_CiviCRM_4.2/master/cbm_plugin_civi-4-2.patch"



; Themes
projects[adminimal_theme][version] = "1.24"

projects[megatron][download][type] = "git"
projects[megatron][download][url] = "https://github.com/ubc-web-services/Megatron.git"
projects[megatron][subdir] = "custom"
projects[megatron][type] = "theme"
projects[megatron][version] = "4.0"

; Custom Modules

projects[ubc_accordion][download][type] = "git"
projects[ubc_accordion][download][url] = "https://github.com/ubc-web-services/d7-clf-Accordion.git"
projects[ubc_accordion][subdir] = "custom"
projects[ubc_accordion][type] = "module"

projects[ubc_button_link][download][type] = "git"
projects[ubc_button_link][download][url] = "https://github.com/ubc-web-services/d7-clf-button.git"
projects[ubc_button_link][subdir] = "custom"
projects[ubc_button_link][type] = "module"

projects[ubc_ckeditor_accessibility][download][type] = "git"
projects[ubc_ckeditor_accessibility][download][url] = "https://github.com/ubc-web-services/ubc_ckeditor_accessibilty.git"
projects[ubc_ckeditor_accessibility][subdir] = "custom"
projects[ubc_ckeditor_accessibility][type] = "module"

projects[ubc_ckeditor_chart][download][type] = "git"
projects[ubc_ckeditor_chart][download][url] = "https://github.com/ubc-web-services/ubc_ckeditor_chart.git"
projects[ubc_ckeditor_chart][subdir] = "custom"
projects[ubc_ckeditor_chart][type] = "module"

projects[ubc_ckeditor_plugins][download][type] = "git"
projects[ubc_ckeditor_plugins][download][url] = "https://github.com/ubc-web-services/d7_ubc_ckeditor_plugins.git"
projects[ubc_ckeditor_plugins][subdir] = "custom"
projects[ubc_ckeditor_plugins][type] = "module"


; Custom Modules in Private Repo
projects[private-mod1][download][type] = "git"
projects[private-mod1][download][url] = "git@github.com:ubc-web-services/private_d7_mods.git"
projects[private-mod1][subdir] = "custom"
projects[private-mod1][type] = "module"




; Libraries

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;libraries[wvega-timepicker][download][type] = ""
;libraries[wvega-timepicker][download][url] = ""
;libraries[wvega-timepicker][directory_name] = "wvega-timepicker"
;libraries[wvega-timepicker][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;libraries[jquery.imagesloaded][download][type] = ""
;libraries[jquery.imagesloaded][download][url] = ""
;libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
;libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;libraries[getid3][download][type] = ""
;libraries[getid3][download][url] = ""
;libraries[getid3][directory_name] = "getid3"
;libraries[getid3][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;libraries[tinymce][download][type] = ""
;libraries[tinymce][download][url] = ""
;libraries[tinymce][directory_name] = "tinymce"
;libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
;libraries[jquery.ui][download][type] = ""
;libraries[jquery.ui][download][url] = ""
;libraries[jquery.ui][directory_name] = "jquery.ui"
;libraries[jquery.ui][type] = "library"




libraries[jquery.imgareaselect][download][type] = "git"
libraries[jquery.imgareaselect][download][url] = "https://github.com/odyniec/imgareaselect.git"
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][download][tag] = "v0.9.10"
libraries[jquery.imgareaselect][type] = "library"

libraries[chosen][download][type] = "git"
libraries[chosen][download][url] = "https://github.com/harvesthq/chosen.git"
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

